on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: python setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Checking pip 
      run:  python -m ensurepip --upgrade

    - name: Install
      run: pip install ${{github.workspace}}

    - name: Test
      working-directory: ${{github.workspace}}/test
      run: python -m unittest 

    # - name: Build package
    #   if: github.event_name == 'push'
    #   run: python setup.py bdist_wheel

    # - name: Publish to pypi
    #   if: github.event_name == 'push'
    #   run: |
    #     jf rt u "dist/*.whl" "Development/"