name: "CI unit tests"
on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          concurrent_skipping: 'never'
          skip_after_successful_duplicate: 'true'
          paths_ignore: '["**/README.md", "**/docs/**","**/conda.recipe/**"]'
          do_not_skip: '["workflow_dispatch", "schedule"]'


  test:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: python setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Checking pip 
      run:  python -m ensurepip --upgrade

    - name: install pdoc3
      run: pip install pdoc3

    - name: Install
      run: pip install ${{github.workspace}}

    - name: Test
      working-directory: ${{github.workspace}}/test
      run: python -m unittest 

    - name: Build docs
      run: pdoc --html quera_ahs_utils -o ${{github.workspace}}/docs