name: 'Build and Deploy documentation'

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
    branches:
      - main
    types: [opened]

jobs:
  # Build job
  test_and_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: python setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Checking pip 
      run:  python -m ensurepip --upgrade

    - name: install pdoc3
      run: pip install pdoc3

    - name: Install
      run: pip install ${{github.workspace}}

    - name: Test
      working-directory: ${{github.workspace}}/test
      run: python -m unittest 

    - name: Build docs
      run: pdoc --html quera_ahs_utils 

    - name: Move assests
      run: mv ${{github.workspace}}/html/quera_ahs_utils/* ${{github.workspace}}/docs/
    
    - name: Commit changes
      uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      with:
        add: '${{github.workspace}}/docs/'
        message: 'updating docs/'