on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install build dependencies
      env:
        PIP_INDEX_URL: ${{ secrets.PIP_INDEX_URL }}     
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        pip install -e .

    - name: Run Unit Tests
      run: |
        python -m pytest -v tests/quetzal_test

    - name: Build package
      if: github.event_name == 'push'
      run: python setup.py bdist_wheel
    
    - name: Setup Artifactory
      if: github.event_name == 'push'
      uses: jfrog/setup-jfrog-cli@v2
      with:
        version: 2.24.3
      env:
        # JFrog platform url (for example: https://acme.jfrog.io) 
        JF_URL: '${{ secrets.JF_URL }}'
        
        # JFrog Platform access token
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
    
    - name: Publish to Artifactory
      if: github.event_name == 'push'
      run: |
        jf rt u "dist/*.whl" "Development/"